version: '3.9'

services:
  app:
    image: grpc-go
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "postgres"
    env_file  :
      - .env
    profiles:
      - db

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - 5432:5432
    profiles:
      - db
    volumes:
      - ./migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/000001_init.up.sql

  in_memory:
    container_name: in_memory
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    profiles:
      - memory
    volumes:
      - .:/app/